# gz topic published by the JointState plugin
- ros_topic_name: "joint_states"
  gz_topic_name: "joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "ignition.msgs.Model" # In future, this will be gz.msgs.Model
  direction: GZ_TO_ROS

# gz topic subscribed by the JointPositionController plugin
- ros_topic_name: "model/mycobot_320pi/joint/joint2_to_joint1/cmd_pos"
  gz_topic_name: "model/mycobot_320pi/joint/joint2_to_joint1/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double" # In future, this will be gz.msgs.Double
  direction: ROS_TO_GZ

- ros_topic_name: "model/mycobot_320pi/joint/joint3_to_joint2/cmd_pos"
  gz_topic_name: "model/mycobot_320pi/joint/joint3_to_joint2/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double" # In future, this will be gz.msgs.Double
  direction: ROS_TO_GZ

- ros_topic_name: "model/mycobot_320pi/joint/joint4_to_joint3/cmd_pos"
  gz_topic_name: "model/mycobot_320pi/joint/joint4_to_joint3/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double" # In future, this will be gz.msgs.Double
  direction: ROS_TO_GZ

- ros_topic_name: "model/mycobot_320pi/joint/joint5_to_joint4/cmd_pos"
  gz_topic_name: "model/mycobot_320pi/joint/joint5_to_joint4/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double" # In future, this will be gz.msgs.Double
  direction: ROS_TO_GZ

- ros_topic_name: "model/mycobot_320pi/joint/joint6_to_joint5/cmd_pos"
  gz_topic_name: "model/mycobot_320pi/joint/joint6_to_joint5/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double" # In future, this will be gz.msgs.Double
  direction: ROS_TO_GZ

- ros_topic_name: "model/mycobot_320pi/joint/joint6output_to_joint6/cmd_pos"
  gz_topic_name: "model/mycobot_320pi/joint/joint6output_to_joint6/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double" # In future, this will be gz.msgs.Double
  direction: ROS_TO_GZ
